path:
  input_data_path: "data/raw/fake_users.csv"
  output_data_root: "data/processed/"
  models_root: "models"
  logs_root: "logs"

features:
 - "category_interaction"
 - "event_distribution"
 - "event_frequency"

model:
  name: "Linear"
  version: 1
  epoch: 50
  early_stopping_patience: 10
